### ISSUE TITLE
Preview Code

### ISSUE THREAD

**Issue by SoPat712** [chkpwd/alfred-workflows#1]
Add a preview for the code, like shown below:

![image](https://github.com/user-attachments/assets/e9e4a31c-3d68-4186-85e3-b60e556dd5ee)

**Comment by SoPat712** [comment]
done too

**Comment by chkpwd** [comment]
Should be ready to submit PRs now. I'm working on refactoring a lot of the code to use native functions to PyOTP.

**Comment by SoPat712** [comment]
got it, thanks
