### ISSUE TITLE
Don't require enter press to run search

### ISSUE THREAD

**Issue by SoPat712** [chkpwd/alfred-workflows#2]

**Comment by chkpwd** [comment]
I would rather keep all workflows that I make (moving forward) tied to this repo for consolidation purposes. If you could submit the PRs here, that would be lovely.

**Comment by SoPat712** [comment]
Alright, if that's specifically what you'd like then I have no objections, I'll submit a PR later today. I'm just fixing my fork right now. How's this look to you?

![image](https://github.com/user-attachments/assets/8d9ad4e7-89c7-413a-9c46-bc5782d7b07b)

**Comment by SoPat712** [comment]
Next course of action for me is that i'd like to get icons

**Comment by chkpwd** [comment]
> Alright, if that's specifically what you'd like then I have no objections, I'll submit a PR later today. I'm just fixing my fork right now. How's this look to you?
> 
> ![image](https://private-user-images.githubusercontent.com/30350506/359992301-f40f847e-b6aa-4ac1-beab-192203c281b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTYzNTQsIm5iZiI6MTcyNDI1NjA1NCwicGF0aCI6Ii8zMDM1MDUwNi8zNTk5OTIzMDEtZjQwZjg0N2UtYjZhYS00YWMxLWJlYWItMTkyMjAzYzI4MWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE2MDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNWM4Y2QzZTA3OWU1NmM5OTIzNjY3NzA5NDBiODBlNDZjZDRmZWM4YTc5NjAzZDRhMDJkOTk3ZTk1ZDE2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQf-13FX7acQB_xaDjWQQrl0UnA__aazX5bK8FooQVA)

That looks fine.
